#include "country.hpp"

namespace Player
{
  std::string countryToString(const Country &country)
  {
    switch (country)
    {
    case Country::AD:
      return "ad";
    case Country::AE:
      return "ae";
    case Country::AF:
      return "af";
    case Country::AG:
      return "ag";
    case Country::AI:
      return "ai";
    case Country::AL:
      return "al";
    case Country::AM:
      return "am";
    case Country::AN:
      return "an";
    case Country::AO:
      return "ao";
    case Country::AQ:
      return "aq";
    case Country::AR:
      return "ar";
    case Country::AS:
      return "as";
    case Country::AT:
      return "at";
    case Country::AU:
      return "au";
    case Country::AW:
      return "aw";
    case Country::AX:
      return "ax";
    case Country::AZ:
      return "az";
    case Country::BA:
      return "ba";
    case Country::BB:
      return "bb";
    case Country::BD:
      return "bd";
    case Country::BE:
      return "be";
    case Country::BF:
      return "bf";
    case Country::BG:
      return "bg";
    case Country::BH:
      return "bh";
    case Country::BI:
      return "bi";
    case Country::BJ:
      return "bj";
    case Country::BL:
      return "bl";
    case Country::BM:
      return "bm";
    case Country::BN:
      return "bn";
    case Country::BO:
      return "bo";
    case Country::BQ:
      return "bq";
    case Country::BR:
      return "br";
    case Country::BS:
      return "bs";
    case Country::BT:
      return "bt";
    case Country::BV:
      return "bv";
    case Country::BW:
      return "bw";
    case Country::BY:
      return "by";
    case Country::BZ:
      return "bz";
    case Country::CA:
      return "ca";
    case Country::CC:
      return "cc";
    case Country::CD:
      return "cd";
    case Country::CF:
      return "cf";
    case Country::CG:
      return "cg";
    case Country::CH:
      return "ch";
    case Country::CI:
      return "ci";
    case Country::CK:
      return "ck";
    case Country::CL:
      return "cl";
    case Country::CM:
      return "cm";
    case Country::CN:
      return "cn";
    case Country::CO:
      return "co";
    case Country::CR:
      return "cr";
    case Country::CU:
      return "cu";
    case Country::CV:
      return "cv";
    case Country::CW:
      return "cw";
    case Country::CX:
      return "cx";
    case Country::CY:
      return "cy";
    case Country::CZ:
      return "cz";
    case Country::DE:
      return "de";
    case Country::DJ:
      return "dj";
    case Country::DK:
      return "dk";
    case Country::DM:
      return "dm";
    case Country::DO:
      return "do";
    case Country::DZ:
      return "dz";
    case Country::EC:
      return "ec";
    case Country::EE:
      return "ee";
    case Country::EG:
      return "eg";
    case Country::EH:
      return "eh";
    case Country::ER:
      return "er";
    case Country::ES:
      return "es";
    case Country::ET:
      return "et";
    case Country::EU:
      return "eu";
    case Country::FI:
      return "fi";
    case Country::FJ:
      return "fj";
    case Country::FK:
      return "fk";
    case Country::FM:
      return "fm";
    case Country::FO:
      return "fo";
    case Country::FR:
      return "fr";
    case Country::GA:
      return "ga";
    case Country::GBNG:
      return "gb-ng";
    case Country::GBIR:
      return "gb-ir";
    case Country::GBCT:
      return "gb-ct";
    case Country::GBLS:
      return "gb-ls";
    case Country::GB:
      return "gb";
    case Country::GD:
      return "gd";
    case Country::GE:
      return "ge";
    case Country::GF:
      return "gf";
    case Country::GG:
      return "gg";
    case Country::GH:
      return "gh";
    case Country::GI:
      return "gi";
    case Country::GL:
      return "gl";
    case Country::GM:
      return "gm";
    case Country::GN:
      return "gn";
    case Country::GP:
      return "gp";
    case Country::GQ:
      return "gq";
    case Country::GR:
      return "gr";
    case Country::GS:
      return "gs";
    case Country::GT:
      return "gt";
    case Country::GU:
      return "gu";
    case Country::GW:
      return "gw";
    case Country::GY:
      return "gy";
    case Country::HK:
      return "hk";
    case Country::HM:
      return "hm";
    case Country::HN:
      return "hn";
    case Country::HR:
      return "hr";
    case Country::HT:
      return "ht";
    case Country::HU:
      return "hu";
    case Country::ID:
      return "id";
    case Country::IE:
      return "ie";
    case Country::IL:
      return "il";
    case Country::IM:
      return "im";
    case Country::IN:
      return "in";
    case Country::IO:
      return "io";
    case Country::IQ:
      return "iq";
    case Country::IR:
      return "ir";
    case Country::IS:
      return "is";
    case Country::IT:
      return "it";
    case Country::JE:
      return "je";
    case Country::JM:
      return "jm";
    case Country::JO:
      return "jo";
    case Country::JP:
      return "jp";
    case Country::KE:
      return "ke";
    case Country::KG:
      return "kg";
    case Country::KH:
      return "kh";
    case Country::KI:
      return "ki";
    case Country::KM:
      return "km";
    case Country::KN:
      return "kn";
    case Country::KP:
      return "kp";
    case Country::KR:
      return "kr";
    case Country::KW:
      return "kw";
    case Country::KY:
      return "ky";
    case Country::KZ:
      return "kz";
    case Country::LA:
      return "la";
    case Country::LB:
      return "lb";
    case Country::LC:
      return "lc";
    case Country::LI:
      return "li";
    case Country::LK:
      return "lk";
    case Country::LR:
      return "lr";
    case Country::LS:
      return "ls";
    case Country::LT:
      return "lt";
    case Country::LU:
      return "lu";
    case Country::LV:
      return "lv";
    case Country::LY:
      return "ly";
    case Country::MA:
      return "ma";
    case Country::MC:
      return "mc";
    case Country::MD:
      return "md";
    case Country::ME:
      return "me";
    case Country::MF:
      return "mf";
    case Country::MG:
      return "mg";
    case Country::MH:
      return "mh";
    case Country::MK:
      return "mk";
    case Country::ML:
      return "ml";
    case Country::MM:
      return "mm";
    case Country::MN:
      return "mn";
    case Country::MO:
      return "mo";
    case Country::MP:
      return "mp";
    case Country::MQ:
      return "mq";
    case Country::MR:
      return "mr";
    case Country::MS:
      return "ms";
    case Country::MT:
      return "mt";
    case Country::MU:
      return "mu";
    case Country::MV:
      return "mv";
    case Country::MW:
      return "mw";
    case Country::MX:
      return "mx";
    case Country::MY:
      return "my";
    case Country::MZ:
      return "mz";
    case Country::NA:
      return "na";
    case Country::NC:
      return "nc";
    case Country::NE:
      return "ne";
    case Country::NF:
      return "nf";
    case Country::NG:
      return "ng";
    case Country::NI:
      return "ni";
    case Country::NL:
      return "nl";
    case Country::NO:
      return "no";
    case Country::NP:
      return "np";
    case Country::NR:
      return "nr";
    case Country::NU:
      return "nu";
    case Country::NZ:
      return "nz";
    case Country::OM:
      return "om";
    case Country::PA:
      return "pa";
    case Country::PE:
      return "pe";
    case Country::PF:
      return "pf";
    case Country::PG:
      return "pg";
    case Country::PH:
      return "ph";
    case Country::PK:
      return "pk";
    case Country::PL:
      return "pl";
    case Country::PM:
      return "pm";
    case Country::PN:
      return "pn";
    case Country::PR:
      return "pr";
    case Country::PS:
      return "ps";
    case Country::PT:
      return "pt";
    case Country::PW:
      return "pw";
    case Country::PY:
      return "py";
    case Country::QA:
      return "qa";
    case Country::RE:
      return "re";
    case Country::RO:
      return "ro";
    case Country::RS:
      return "rs";
    case Country::RU:
      return "ru";
    case Country::RW:
      return "rw";
    case Country::SA:
      return "sa";
    case Country::SB:
      return "sb";
    case Country::SC:
      return "sc";
    case Country::SD:
      return "sd";
    case Country::SE:
      return "se";
    case Country::SG:
      return "sg";
    case Country::SH:
      return "sh";
    case Country::SI:
      return "si";
    case Country::SJ:
      return "sj";
    case Country::SK:
      return "sk";
    case Country::SL:
      return "sl";
    case Country::SM:
      return "sm";
    case Country::SN:
      return "sn";
    case Country::SO:
      return "so";
    case Country::SR:
      return "sr";
    case Country::SS:
      return "ss";
    case Country::ST:
      return "st";
    case Country::SV:
      return "sv";
    case Country::SX:
      return "sx";
    case Country::SY:
      return "sy";
    case Country::SZ:
      return "sz";
    case Country::TC:
      return "tc";
    case Country::TD:
      return "td";
    case Country::TF:
      return "tf";
    case Country::TG:
      return "tg";
    case Country::TH:
      return "th";
    case Country::TJ:
      return "tj";
    case Country::TK:
      return "tk";
    case Country::TL:
      return "tl";
    case Country::TM:
      return "tm";
    case Country::TN:
      return "tn";
    case Country::TO:
      return "to";
    case Country::TR:
      return "tr";
    case Country::TT:
      return "tt";
    case Country::TV:
      return "tv";
    case Country::TW:
      return "tw";
    case Country::TZ:
      return "tz";
    case Country::UA:
      return "ua";
    case Country::UG:
      return "ug";
    case Country::UM:
      return "um";
    case Country::US:
      return "us";
    case Country::UY:
      return "uy";
    case Country::UZ:
      return "uz";
    case Country::VA:
      return "va";
    case Country::VC:
      return "vc";
    case Country::VE:
      return "ve";
    case Country::VG:
      return "vg";
    case Country::VI:
      return "vi";
    case Country::VN:
      return "vn";
    case Country::VU:
      return "vu";
    case Country::WF:
      return "wf";
    case Country::XK:
      return "xk";
    case Country::WS:
      return "ws";
    case Country::YE:
      return "ye";
    case Country::YT:
      return "yt";
    case Country::ZA:
      return "za";
    case Country::ZM:
      return "zm";
    case Country::ZW:
      return "zw";
    default:
      return "Unknown";
    }
  }
}