#include "cardtype.h"

std::string getCardName(const CardType &card)
{
  switch (card)
  {
  case CardType::COMMON_BRONZE:
    return "COMMON_BRONZE";
  case CardType::COMMON_SILVER:
    return "COMMON_SILVER";
  case CardType::COMMON_GOLD:
    return "COMMON_GOLD";
  case CardType::RARE_BRONZE:
    return "RARE_BRONZE";
  case CardType::RARE_SILVER:
    return "RARE_SILVER";
  case CardType::RARE_GOLD:
    return "RARE_GOLD";
  case CardType::IF_BRONZE:
    return "IF_BRONZE";
  case CardType::IF_SILVER:
    return "IF_SILVER";
  case CardType::IF_GOLD:
    return "IF_GOLD";
  case CardType::FC_BRONZE:
    return "FC_BRONZE";
  case CardType::FC_SILVER:
    return "FC_SILVER";
  case CardType::FC_GOLD:
    return "FC_GOLD";
  case CardType::MOTM:
    return "MOTM";
  case CardType::PL_POTM:
    return "PL_POTM";
  case CardType::BL_POTM:
    return "BL_POTM";
  case CardType::FUTTIES:
    return "FUTTIES";
  case CardType::FUTTIESW:
    return "FUTTIESW";
  case CardType::TOTY:
    return "TOTY";
  case CardType::TOTY_N:
    return "TOTY_N";
  case CardType::EL:
    return "EL";
  case CardType::EL_MOTM:
    return "EL_MOTM";
  case CardType::EL_LIVE:
    return "EL_LIVE";
  case CardType::EL_SBC:
    return "EL_SBC";
  case CardType::EL_TOTT:
    return "EL_TOTT";
  case CardType::COMMON_UCL:
    return "COMMON_UCL";
  case CardType::RARE_UCL:
    return "RARE_UCL";
  case CardType::UCL_MOTM:
    return "UCL_MOTM";
  case CardType::UCL_LIVE:
    return "UCL_LIVE";
  case CardType::UCL_SBC:
    return "UCL_SBC";
  case CardType::UCL_TOTT:
    return "UCL_TOTT";
  case CardType::FSR:
    return "FSR";
  case CardType::FS:
    return "FS";
  case CardType::FSN:
    return "FSN";
  case CardType::PP:
    return "PP";
  case CardType::CB:
    return "CB";
  case CardType::RB:
    return "RB";
  case CardType::HERO:
    return "HERO";
  case CardType::AW:
    return "AW";
  case CardType::FB:
    return "FB";
  case CardType::HEADLINERS:
    return "HEADLINERS";
  case CardType::CC:
    return "CC";
  case CardType::SBC:
    return "SBC";
  case CardType::SBCP:
    return "SBCP";
  case CardType::LEGEND:
    return "LEGEND";
  default:
    return "Unknown";
  }
}