name: Publish API Docker Image

on:
  release:
    types: [created]

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Load .env file
        run: |
          set -o allexport
          source .env
          echo "VERSION=${VERSION}-api" >> $GITHUB_ENV
          set +o allexport

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          file: ./docker/Dockerfile.api
          tags: eoussama/fut-card-generator:${{ env.VERSION }}
